"""create users table

Adds the account table. Two things the autogenerated draft did not handle are
done explicitly here:

- The ``citext`` extension is enabled before the table that uses it. Like
  pgvector in migration 0001, the extension is schema state and belongs in a
  migration, not an image init script, so it exists on every database the
  migration runs against -- local, CI, and managed Postgres alike.
- The downgrade drops the table but deliberately does not drop the ``citext``
  extension. Another object could come to depend on it, and a non-cascading
  drop that fails loudly is safer than one that removes a type other tables
  are still using. The extension is cheap to leave installed.

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-21

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Enable citext and create the users table."""
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )


def downgrade() -> None:
    """Drop the users table, leaving the citext extension in place."""
    op.drop_table("users")
